### PR TITLE
[JENKINS-25726, JENKINS-25771] - StartedByUser and StartedByMemberOfGroup restrictions

### PR DESCRIPTION
**Pull request by oleg-nenashev**
The current version is just a draft

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
The PR should be reworked to be error-robust. I'm going to take the implementation from #6 after the merge

**Comment by oleg-nenashev** [comment]
@csms 
The changes works well for user causes.
Could you check it for groups?

I'll definitely develop several unit tests, but now we need a manual check

**Comment by csms** [comment]
is it on this pull request that I should test?

**Comment by oleg-nenashev** [comment]
Yep. I merged your changes to this PR.

**Comment by csms** [comment]
Following test setup:
Plugin setup:
Mock Security Realm(used as realm)
Parameterized Trigger Plugin
Parameterized Remote Trigger Plugin

job setup:
parent 
 - child during build
   - grandchild during build
   - grandchild after build
 - child after build
   - grandchild during build
   - grandchild after build

Node setup:
- Mocknode1
   - 10 executors
   - allow members of group mocknode1 to start jobs
- Mocknode2
   - 10 executors
   - allow members of group mocknode2 to start jobs

Principal setup:
User mocknode1 - group mocknode1
User mocknode2 - group mocknode2

**Comment by csms** [comment]
I started parent job with nodelabel set to mocknode1 logged in as mocknode1.

It looks like the row:
final @CheckForNull User usr = User.get(userId, false, null); 
returns null when called in acceptUser.

Is there any better way/other way you prefer that I report this/show these? 
I think I fetched the user like this:
SecurityRealm sr = Jenkins.getInstance().getSecurityRealm();
UserDetails userDetails = sr.loadUserByUsername(userId);

**Comment by oleg-nenashev** [comment]
We can use the initial implementation as a fallback.
If I understand correctly, the user has not been registered in Jenkins when you started the test

**Comment by csms** [comment]
If you mean that they are not in "jenkin's own user database" then yes. They are in a realm, in this case the mock realm. I don't know wether requests to User.get normally get propagated to the realm but at least in this case it doesn't seem that way :-(.

**Comment by csms** [comment]
As far as I understand I don't have permissions to change the code in this pr right?

**Comment by oleg-nenashev** [comment]
You can create a pull request to https://github.com/jenkinsci/job-restrictions-plugin/tree/JENKINS-25726.
If you want, I can grant you permissions to update this branch directly

**Comment by csms** [comment]
It's ok, whatever works best for you, I can also report my findings here if you want to change the code.

**Pull request merged**
