### PR TITLE
Migrate into localization-zh-cn-plugin

### PR DESCRIPTION
**Pull request by LinuxSuRen**
See https://github.com/jenkinsci/localization-zh-cn-plugin

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
@jenkinsci/code-reviewers Anyone could take some time to help me review this pr? Thanks.

**Comment by LinuxSuRen** [comment]
A friendly reminder @oleg-nenashev

**Comment by tusharchaudhari30** [comment]
Yup that is working good..

**Comment by oleg-nenashev** [comment]
I put this plugin to adoption a while ago, not adopted so far. I will merge it since it is a small change, but no ETA of the release

**Pull request merged**
